### ISSUE TITLE
[Suggestion] Allow compacting drawers to compact ore pieces into chunks

### ISSUE THREAD

**Issue by Sheyin** [CritFlaw/EggBox#2]
It'd be nice to allow storage drawers to compact ore pieces as a quality of life improvement!  It'd also make it less likely that there'd be problems with item overflow.  It isn't allowed by default, but it seems that custom configs in Stoneblock makes this possible.  Thanks!

**Comment by CritFlaw** [comment]
Great idea. Changed.
